#!/bin/bash
#start this script by typing: bash <(curl -sL https://raw.githubusercontent.com/SET-LTD/hexfiles/master/rpi)
echo "          _____                    _____                _____           ";
echo "         /\    \                  /\    \              /\    \          ";
echo "        /::\    \                /::\    \            /::\    \         ";
echo "       /::::\    \              /::::\    \           \:::\    \        ";
echo "      /::::::\    \            /::::::\    \           \:::\    \       ";
echo "     /:::/\:::\    \          /:::/\:::\    \           \:::\    \      ";
echo "    /:::/__\:::\    \        /:::/__\:::\    \           \:::\    \     ";
echo "    \:::\   \:::\    \      /::::\   \:::\    \          /::::\    \    ";
echo "  ___\:::\   \:::\    \    /::::::\   \:::\    \        /::::::\    \   ";
echo " /\   \:::\   \:::\    \  /:::/\:::\   \:::\    \      /:::/\:::\    \  ";
echo "/::\   \:::\   \:::\____\/:::/__\:::\   \:::\____\    /:::/  \:::\____\ ";
echo "\:::\   \:::\   \::/    /\:::\   \:::\   \::/    /   /:::/    \::/    / ";
echo " \:::\   \:::\   \/____/  \:::\   \:::\   \/____/   /:::/    / \/____/  ";
echo "  \:::\   \:::\    \       \:::\   \:::\    \      /:::/    /           ";
echo "   \:::\   \:::\____\       \:::\   \:::\____\    /:::/    /            ";
echo "    \:::\  /:::/    /        \:::\   \::/    /    \::/    /             ";
echo "     \:::\/:::/    /          \:::\   \/____/      \/____/              ";
echo "      \::::::/    /            \:::\    \                               ";
echo "       \::::/    /              \:::\____\                              ";
echo "        \::/    /                \::/    /                              ";
echo "         \/____/                  \/____/                               ";
echo "                                                                        ";

echo "Starting Jakubs Script to install all software from clean image      ";

read -p "Do you wish to auto configure SSL?  Input y/n and hit enter: " askssl
read -p "Do you wish to auto configure static?  Input y/n and hit enter: " staticxxx


if [ "$staticxxx" = y ] ; then

read -p "What static ip adress would you like?  Input example 192.168.0.99 and hit enter: " dhcp_static_client
read -p "What is the adress of the gateway?  Input example 192.168.0.1 and hit enter: " dhcp_static_gateway

read -p "Do you wish to auto configure ethernet or wifi?  Input e/w and hit enter: " staticyyy
read -p "Do you wish to configure x509?  Input y/n and hit enter: " staticx509
     if [ "$staticx509" = y ] ; then
     #update the node-red settings.js
     #wget
     #restart will be required
     sudo wget https://raw.githubusercontent.com/SET-LTD/hexfiles/master/settings.jsx509 -P /etc/
     rm settings.js
     sudo mv /home/pi/.node-red/settings.jsx509 /home/pi/.node-red/settings.js
     else
     fi
 if [ "$staticy" = w ] ; then

 #download wifi template
sudo wget https://raw.githubusercontent.com/SET-LTD/hexfiles/master/my_wget_dhcp_wlan -P /etc/
sudo mv /etc/my_wget_dhcp_wlan /etc/dhcpcd.conf




 else
 #download ethernet template
 sudo wget https://raw.githubusercontent.com/SET-LTD/hexfiles/master/my_wget_dhcp_eth -P /etc/
 sudo mv /etc/my_wget_dhcp_eth /etc/dhcpcd.conf
  
 fi
 
 #configure settings here
  sudo sed -i "s/kkk/${dhcp_static_client}/g" /etc/dhcpcd.conf
  sudo sed -i "s/mmm/${dhcp_static_gateway}/g" /etc/dhcpcd.conf

else
  echo "not configuring static settings"
fi


sudo apt-get update
sudo wget https://raw.githubusercontent.com/SET-LTD/hexfiles/master/cron_can.sh -P /home/pi/
sudo chmod +x /home/pi/cron_can.sh
sudo crontab -l | { cat; echo "@reboot /home/pi/cron_can.sh"; } | crontab

sudo apt-get install can-utils
sudo apt-get install putty-tools

cd
mkdir ~/.ssh
cd .ssh

ssh-keygen -f id_rsa -N ""
#generate keys no passfrase
cat id_rsa.pub >> authorized_keys
#activate key
puttygen id_rsa -o id_rsa.ppk
#convert key file to putty format
#use private key to login
#To download key from other computer
#scp pi@192.168.0.199:/home/pi/.ssh/id_rsa .
#To login on other computer
#ssh -i id_rsa pi@192.168.0.199



cd

sudo apt install build-essential git -y
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
cd /home/pi/.node-red/
sudo npm install -g node-red-admin
sudo npm install node-red-dashboard
sudo npm install node-red-contrib-arp
sudo npm install node-red-contrib-browser-utils
sudo npm install node-red-contrib-safe-queue
#sudo npm install node-red-contrib-socketcan
sudo npm install red-contrib-socketcan
mkdir /home/pi/.node-red/nodecerts

cd /home/pi/.node-red/nodecerts
openssl genrsa -out privatekey.pem 2048 
#next command needs fillin out
openssl req -new -key privatekey.pem -out private-csr.pem<<EOF
GB
Derbyshire
Derby
SET
HQ
192.168.0.200
jakubwton@aol.com
Test123
SET
EOF

openssl x509 -req -days 3560 -in private-csr.pem -signkey privatekey.pem -out certificate.pem
openssl x509 -outform der -in certificate.pem -out certificate.crt


sudo sed -i -e "\$adtparam=spi=on" /boot/config.txt
sudo sed -i -e "\$adtoverlay=mcp2515-can0,oscillator=16000000,interrupt=25" /boot/config.txt
sudo sed -i -e "\$adtoverlay=spi-bcm2835-overlay" /boot/config.txt
echo "Fixing usb not working cm4 hub      ";

sudo sed -i -e "dtoverlay=dwc2,dr_mode=host" /boot/config.txt

sudo systemctl enable nodered.service

cd /home/pi
rm -rf cliflash
mkdir temp
cd temp
wget https://github.com/PaulStoffregen/teensy_loader_cli/archive/master.zip
sudo apt-get install libusb-dev
unzip master.zip
mv teensy_loader_cli-master cliflash
mv cliflash  /home/pi
cd /home/pi
rm -rf temp
cd /home/pi/cliflash
make
cd /home/pil
sed -i -e  "\$aPATH=\$PATH:/home/pi/cliflash"  .bashrc
sudo wget https://www.pjrc.com/teensy/49-teensy.rules -P /etc/udev/rules.d

cd /home/pi
sudo apt-get install moreutils -y
sudo apt-get install dnsutils -y
sudo apt-get install git -y
myhostnamedot="$(dig -x $(dig +short myip.opendns.com @resolver1.opendns.com) +short)"
myhostname=`echo $myhostnamedot | sed "s/\.$//"`


cd /home/pi
sudo wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key -P /home/pi
sudo apt-key add /home/pi/mosquitto-repo.gpg.key
sudo wget http://repo.mosquitto.org/debian/mosquitto-buster.list -P /etc/apt/sources.list.d
sudo apt-get update
#sudo apt-get install mosquitto -y
if [ "$askssl" = y ] ; then
  sudo rm /etc/mosquitto/mosquitto.conf
  sudo wget https://raw.githubusercontent.com/SET-LTD/hexfiles/master/mosquitto.conf -P /etc/mosquitto
  sudo sed -i "s/xxx/${myhostname}/g" /etc/mosquitto/mosquitto.conf
else
  echo "not configured mosquitto SSL"
fi
cd /home/pi
#sudo apt-get install nginx-full certbot -y
if [ "$askssl" = y ] ; then
  sudo rm /etc/nginx/sites-enabled/default
  sudo rm /etc/nginx/sites-available/default
  sudo wget https://raw.githubusercontent.com/SET-LTD/hexfiles/master/node -P /etc/nginx/sites-available
  sudo sed -i "s/xxx/${myhostname}/g" /etc/nginx/sites-available/node
  sudo ln -s /etc/nginx/sites-available/node /etc/nginx/sites-enabled/node
  sudo certbot certonly  --authenticator standalone -d ${myhostname}  --pre-hook "service nginx stop" --post-hook "service nginx start"
else
  echo "not configured nginx SSL"
fi

sudo node-red-stop


#cd /home/pi/.node-red/
#sudo nano settings.js

#editorTheme: {
#        projects: {
#            // To enable the Projects feature, set this value to true
#            enabled: false
#        }
#    }
